import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My-Eccomerce",
  description: "Generated by create next app",
};

import "./globals.css";
import { ProductsContextProvider } from "@/components/ProductsContext";

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ProductsContextProvider>{children}</ProductsContextProvider>
      </body>
      </html>
  )
  
}
